Transpose of the matrix

In [1]:
import numpy as np
matrix = np.array([
    [1, 0.2, 0.5],
    [0.2, 1, 0.8],
    [0.5, 0.8, 1]])

In [2]:
# Finding the transpose using NumPy's transpose function
transpose_matrix = np.transpose(matrix)

In [3]:
# Printing the original matrix and its transpose
print("Original Matrix:")
print(matrix)

print("\nTranspose Matrix:")
print(transpose_matrix)


Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Transpose Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


DETERMINANT OF THE MATRIX

In [4]:
import numpy as np
matrix = np.array([
    [1, 0.2, 0.5],
    [0.2, 1, 0.8],
    [0.5, 0.8, 1]])

In [7]:
# Compute the determinant of the matrix
import numpy as np
determinant = np.array
np.array.det(matrix)

AttributeError: 'builtin_function_or_method' object has no attribute 'det'

In [9]:
# Check if the determinant is computable (non-singular matrix)
if determinant != 0:
    print("The determinant of the matrix is:", determinant)
else:
    print("The matrix is singular, determinant cannot be computed.")


The determinant of the matrix is: <built-in function array>


TRANSFORM THE MATRIX

In [7]:
import numpy as np
b = np.array([[1, 0.2, 0.5],
              [0.2, 1, 0.8],
              [0.5, 0.8, 1]])


In [8]:
# Transpose the matrix
transformed_matrix = np.transpose(b)
print(transformed_matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


DECOMPOSE THE MATRIX